### ISSUE TITLE
我在liunx下docker上运行代码出现错了，可以帮帮处理一下吗？

### ISSUE THREAD

**Issue by 66508393** [Yuukiy/JavSP#165]
### 问题详情

python JavSP.py
配置的抓取器无效: javdb, javdb
扫描影片文件...
扫描影片文件：共找到 2 部影片

正在整理: 121423_952.mp4
无法绕开JavLib的反爬机制
整理失败: 为其配置的7个抓取器均未获取到影片信息

正在整理: MOND-225.mp4
整理失败: module 'ctypes' has no attribute 'windll'
sh: 1: pause: not found
root@4d13ed033fec:~/JavSP# pip install ctypes
ERROR: Could not find a version that satisfies the requirement ctypes (from versions: none)
ERROR: No matching distribution found for ctypes
root@4d13ed033fec:~/JavSP# pip install ctypes
ERROR: Could not find a version that satisfies the requirement ctypes (from versions: none)
ERROR: No matching distribution found for ctypes

### 运行方式

我是从源代码运行的

### 代理

否

### 日志

2023-12-15 07:00:45 main:532 DEBUG: ======================JavSP 未知版本/从代码运行======================
2023-12-15 07:00:45 main:65 WARNING: 配置的抓取器无效: javdb, javdb
2023-12-15 07:00:45 core.file:118 DEBUG: 影片数据源类型: 121423_952: normal
2023-12-15 07:00:45 core.file:118 DEBUG: 影片数据源类型: MOND-225: normal
2023-12-15 07:00:45 main:553 INFO: 扫描影片文件：共找到 2 部影片
2023-12-15 07:00:45 main:396 INFO: 正在整理: 121423_952.mp4
2023-12-15 07:00:46 main:85 DEBUG: web.jav321: 未找到影片: '121423_952'
2023-12-15 07:00:46 main:85 DEBUG: web.javbus: 未找到影片: '121423_952'
2023-12-15 07:00:47 web.base:57 DEBUG: 无法通过CloudFlare检测: 'HTTPSConnectionPool(host='www.a66j.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.a66j.com'. (_ssl.c:1131)")))', 尝试退回常规的requests请求
2023-12-15 07:00:47 main:85 DEBUG: web.avsox: 未找到影片: '121423_952'
2023-12-15 07:00:47 web.javlib:45 DEBUG: Fail to connect to 'https://www.a66j.com': HTTPSConnectionPool(host='www.a66j.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'www.a66j.com' doesn't match 'a66j.com'")))
2023-12-15 07:00:47 web.javlib:46 WARNING: 无法绕开JavLib的反爬机制
2023-12-15 07:00:47 web.javlib:57 DEBUG: JavLib网络配置: https://www.javlibrary.com, proxy={}
2023-12-15 07:00:47 main:85 DEBUG: web.prestige: 未找到影片: '121423_952'
2023-12-15 07:00:47 main:85 DEBUG: web.airav: 未找到影片: '121423_952'
2023-12-15 07:00:47 main:85 DEBUG: web.javlib: 未找到影片: '121423_952'
2023-12-15 07:00:48 main:85 DEBUG: web.mgstage: 未找到影片: '121423_952'
2023-12-15 07:00:48 main:462 DEBUG: 为其配置的7个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 402, in RunNormalMode
    check_step(all_info, msg)
  File "JavSP.py", line 388, in check_step
    raise Exception(msg + '\n')
Exception: 为其配置的7个抓取器均未获取到影片信息

2023-12-15 07:00:48 main:463 ERROR: 整理失败: 为其配置的7个抓取器均未获取到影片信息

2023-12-15 07:00:48 main:396 INFO: 正在整理: MOND-225.mp4
2023-12-15 07:00:48 main:79 DEBUG: web.jav321: 抓取成功: 'MOND-225': 'https://en.jav321.com/video/18mond00225'
2023-12-15 07:00:48 main:79 DEBUG: web.javlib: 抓取成功: 'MOND-225': 'https://www.javlibrary.com/cn/?v=javme3bote'
2023-12-15 07:00:48 main:85 DEBUG: web.avsox: 未找到影片: 'MOND-225'
2023-12-15 07:00:49 main:79 DEBUG: web.airav: 抓取成功: 'MOND-225': 'https://www.airav.wiki/video/MOND-225'
2023-12-15 07:00:49 main:85 DEBUG: web.mgstage: 未找到影片: 'MOND-225'
2023-12-15 07:00:49 main:79 DEBUG: web.javbus: 抓取成功: 'MOND-225': 'https://www.javbus.com/MOND-225'
2023-12-15 07:00:49 main:85 DEBUG: web.prestige: 未找到影片: 'MOND-225'
2023-12-15 07:00:49 main:187 DEBUG: 从'airav'中获取了字段: actress cover genre plot preview_pics preview_video producer publish_date title url
2023-12-15 07:00:49 main:187 DEBUG: 从'javbus'中获取了字段: actress_pics cover director duration genre_id publisher serial
2023-12-15 07:00:49 main:187 DEBUG: 从'javlib'中获取了字段: cover score
2023-12-15 07:00:49 main:187 DEBUG: 从'jav321'中获取了字段: cid cover
2023-12-15 07:00:49 main:462 DEBUG: module 'ctypes' has no attribute 'windll'
Traceback (most recent call last):
  File "JavSP.py", line 413, in RunNormalMode
    generate_names(movie)
  File "JavSP.py", line 281, in generate_names
    remaining = get_remaining_path_len(os.path.abspath(fanart_file))
  File "/javsp/JavSP/core/file.py", line 166, in get_remaining_path_len
    is_remote = is_remote_drive(path)
  File "/javsp/JavSP/core/file.py", line 156, in is_remote_drive
    result = ctypes.windll.kernel32.GetDriveTypeW(drive)
AttributeError: module 'ctypes' has no attribute 'windll'
2023-12-15 07:00:49 main:463 ERROR: 整理失败: module 'ctypes' has no attribute 'windll'

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
手动指定一下文件长度可以暂时解决这个问题
# config.ini
calc_path_len_by_byte = 255

**Comment by 66508393** [comment]
/JavSP# python JavSP.py
配置的抓取器无效: javdb, javdb
扫描影片文件...
扫描影片文件：共找到 2 部影片

正在整理: 121423_952.mp4
无法绕开JavLib的反爬机制
整理失败: 为其配置的7个抓取器均未获取到影片信息

正在整理: MOND-225.mp4
重命名文件: '整理完成/加藤ツバキ（夏樹カオル）/[MOND-225] 憧れの女上司と 加藤ツバキ/MOND-225.mp4' -> '.../MOND-225.mp4'
整理完成，相关文件已保存到: /root/JavSP/jk/MOND-225

sh: 1: pause: not found



可以了! 谢谢
