### ISSUE TITLE
希望fanza能够支持里番刮削

### ISSUE THREAD

**Issue by CAT9ACG** [Yuukiy/JavSP#186]
### 功能建议

问题详情
dl_getchu, gyutto这两个网站里番收录的太少，很多无法搜刮到。
相对而言fanza对里番信息收集的比较全面，https://www.dmm.co.jp/mono/anime/-/detail/=/cid=62knbm009/

运行方式
运行打包后的exe程序

代理
是

日志
2024-01-04 19:51:03 main:532 DEBUG: ========================JavSP v1.6.1========================
2024-01-04 19:51:06 core.file:140 DEBUG: 影片数据源类型: 62knbm009: cid
2024-01-04 19:51:06 main:553 INFO: 扫描影片文件：共找到 1 部影片
2024-01-04 19:51:06 main:338 INFO: 进入手动模式检查番号: 
2024-01-04 19:51:16 main:364 INFO: 已更正影片番号: 62knbm009.mp4: cid=62knbm009 -> cid=62knbm009
2024-01-04 19:51:16 main:396 INFO: 正在整理: 62knbm009.mp4
2024-01-04 19:51:18 main:85 DEBUG: web.fanza: 未找到影片: '62knbm009'
2024-01-04 19:51:18 main:462 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 402, in RunNormalMode
  File "JavSP.py", line 388, in check_step
Exception: 为其配置的1个抓取器均未获取到影片信息

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
你这部在getchu也有，只是番号不一样 https://www.getchu.com/soft.phtml?id=1244244&gc=gc

**Comment by CAT9ACG** [comment]
是的getchu有，但我看dl_getchu.py，base_url = 'https://dl.getchu.com' 用的是dl.getchu 不太一样。getchu的话没有影片tag。

**Comment by Yuukiy** [comment]
dl.getchu 是同人作品，getchu是机构作品，我这么理解对么？

**Comment by CAT9ACG** [comment]
是的

**Comment by Yuukiy** [comment]
添加了，在新版本发布前你可以先试试刚打包的版本 https://github.com/Yuukiy/JavSP/actions/runs/7410355582/artifacts/1147666460

**Comment by CAT9ACG** [comment]
非常感谢，目前尝试了一下，像这样的cid:h_402mjad357 会出现 “整理失败: 为其配置的0个抓取器均未获取到影片信息”
https://www.dmm.co.jp/mono/anime/-/detail/=/cid=h_402mjad357

**Comment by CAT9ACG** [comment]
抱歉，我刚才说出了
日志
2024-01-04 22:08:10 core.file:145 DEBUG: 影片数据源类型: mjad-357: normal
2024-01-04 22:08:10 core.file:145 DEBUG: 影片数据源类型: zizd-021: normal
2024-01-04 22:08:10 main:577 INFO: 扫描影片文件：共找到 2 部影片
2024-01-04 22:08:10 main:416 INFO: 正在整理: h_402mjad357.mp4
2024-01-04 22:08:16 main:85 DEBUG: web.fanza: 未找到影片: 'None'
2024-01-04 22:08:16 main:486 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 422, in RunNormalMode
  File "JavSP.py", line 408, in check_step
Exception: 为其配置的1个抓取器均未获取到影片信息

2024-01-04 22:08:16 main:487 ERROR: 整理失败: 为其配置的1个抓取器均未获取到影片信息

2024-01-04 22:08:16 main:416 INFO: 正在整理: h_826zizd021.mp4
2024-01-04 22:08:23 main:85 DEBUG: web.fanza: 未找到影片: 'None'
2024-01-04 22:08:23 main:486 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 422, in RunNormalMode
  File "JavSP.py", line 408, in check_step
Exception: 为其配置的1个抓取器均未获取到影片信息

2024-01-04 22:08:23 main:487 ERROR: 整理失败: 为其配置的1个抓取器均未获取到影片信息

我试了一下你刚才修改的fanza.py 是可以刮削到的。

**Comment by Yuukiy** [comment]
解析不到是因为之前的cid是严格按照AV的cid来解析的，刚刚那部影片的文件名没有被识别为cid，所以没有调fanza。我放宽了解析条件，你可以直接运行代码`python javsp.py`或者去 https://github.com/Yuukiy/JavSP/actions/runs/7410811073 下载新打包的试试

**Comment by CAT9ACG** [comment]
非常感谢开发者大大支持，已经能正常使用了。
