### ISSUE TITLE
网络错误，无法刮削

### ISSUE THREAD

**Issue by zxtcko** [Yuukiy/JavSP#212]
### 问题详情

请选择要整理的文件夹：G:\girls\JAV_output\#安达夕莉\[2023] メイドさんにハマった彼氏に嫉妬して…过激メイドコス全力パイズ リ彼女 安达夕莉 （BOD） [SSIS-957]
扫描影片文件...
扫描影片文件：共找到 1 部影片

正在整理: SSIS-957-C.mp4
无法绕开JavLib的反爬机制
下载封面图片失败
整理失败: 下载封面图片失败

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志
```log
2024-02-13 21:41:11 core.config:412 WARNING: 已创建默认配置文件: 'G:\girls\JavSP-v1.7-Windows-amd64\config.ini'
2024-02-13 21:41:11 main:558 DEBUG: =========================JavSP v1.7=========================
2024-02-13 21:41:32 core.file:145 DEBUG: 影片数据源类型: SSIS-957: normal
2024-02-13 21:41:32 main:579 INFO: 扫描影片文件：共找到 1 部影片
2024-02-13 21:41:32 main:418 INFO: 正在整理: SSIS-957-C.mp4
2024-02-13 21:41:32 main:96 DEBUG: web.avsox: 网络错误，正在重试 (1/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:32 main:96 DEBUG: web.javbus: 网络错误，正在重试 (1/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:32 web.base:57 DEBUG: 无法通过CloudFlare检测: '('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))', 尝试退回常规的requests请求
2024-02-13 21:41:32 main:96 DEBUG: web.mgstage: 网络错误，正在重试 (1/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.mgstage.com/product/product_detail/SSIS-957/')
2024-02-13 21:41:32 main:96 DEBUG: web.avsox: 网络错误，正在重试 (2/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:32 main:96 DEBUG: web.javbus: 网络错误，正在重试 (2/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:32 main:96 DEBUG: web.javdb: 网络错误，正在重试 (1/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:33 main:96 DEBUG: web.avsox: 网络错误，正在重试 (3/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:33 main:96 DEBUG: web.javbus: 网络错误，正在重试 (3/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:33 main:96 DEBUG: web.mgstage: 网络错误，正在重试 (2/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.mgstage.com/product/product_detail/SSIS-957/')
2024-02-13 21:41:33 web.base:57 DEBUG: 无法通过CloudFlare检测: '('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))', 尝试退回常规的requests请求
2024-02-13 21:41:33 main:96 DEBUG: web.javdb: 网络错误，正在重试 (2/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:33 main:96 DEBUG: web.mgstage: 网络错误，正在重试 (3/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.mgstage.com/product/product_detail/SSIS-957/')
2024-02-13 21:41:33 web.base:178 DEBUG: Not connectable: https://www.k72s.com
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:34 web.base:57 DEBUG: 无法通过CloudFlare检测: '('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))', 尝试退回常规的requests请求
2024-02-13 21:41:34 web.javlib:45 DEBUG: Fail to connect to 'https://www.i71t.com': ('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2024-02-13 21:41:34 web.javlib:46 WARNING: 无法绕开JavLib的反爬机制
2024-02-13 21:41:34 web.javlib:57 DEBUG: JavLib网络配置: https://www.javlibrary.com, proxy={}
2024-02-13 21:41:34 web.base:57 DEBUG: 无法通过CloudFlare检测: '('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None))', 尝试退回常规的requests请求
2024-02-13 21:41:36 main:96 DEBUG: web.javdb: 网络错误，正在重试 (3/3): 
ConnectionError(ProtocolError('Connection aborted.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2024-02-13 21:41:37 main:81 DEBUG: web.airav: 抓取成功: 'SSIS-957': 'https://www.airav.wiki/video/SSIS-957'
2024-02-13 21:41:42 main:96 DEBUG: web.jav321: 网络错误，正在重试 (1/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.jav321.com', port=443): Max retries exceeded with url: /search (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102FE310>, 'Connection to www.jav321.com timed out. (connect timeout=10)'))"))
2024-02-13 21:41:42 main:96 DEBUG: web.prestige: 网络错误，正在重试 (1/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.prestige-av.com', port=443): Max retries exceeded with url: /goods/goods_detail.php?sku=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102DE1C0>, 'Connection to www.prestige-av.com timed out. (connect timeout=10)'))"))
2024-02-13 21:41:44 web.base:57 DEBUG: 无法通过CloudFlare检测: 'HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102DE4F0>, 'Connection to www.javlibrary.com timed out. (connect timeout=10)'))', 尝试退回常规的requests请求
2024-02-13 21:41:52 main:96 DEBUG: web.jav321: 网络错误，正在重试 (2/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.jav321.com', port=443): Max retries exceeded with url: /search (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102F2B20>, 'Connection to www.jav321.com timed out. (connect timeout=10)'))"))
2024-02-13 21:41:52 main:96 DEBUG: web.prestige: 网络错误，正在重试 (2/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.prestige-av.com', port=443): Max retries exceeded with url: /goods/goods_detail.php?sku=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102D0A60>, 'Connection to www.prestige-av.com timed out. (connect timeout=10)'))"))
2024-02-13 21:41:54 main:96 DEBUG: web.javlib: 网络错误，正在重试 (1/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A177E0730>, 'Connection to www.javlibrary.com timed out. (connect timeout=10)'))"))
2024-02-13 21:42:02 main:96 DEBUG: web.jav321: 网络错误，正在重试 (3/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.jav321.com', port=443): Max retries exceeded with url: /search (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A177E0940>, 'Connection to www.jav321.com timed out. (connect timeout=10)'))"))
2024-02-13 21:42:02 main:96 DEBUG: web.prestige: 网络错误，正在重试 (3/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.prestige-av.com', port=443): Max retries exceeded with url: /goods/goods_detail.php?sku=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102DE040>, 'Connection to www.prestige-av.com timed out. (connect timeout=10)'))"))
2024-02-13 21:42:04 web.base:57 DEBUG: 无法通过CloudFlare检测: 'HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102DE070>, 'Connection to www.javlibrary.com timed out. (connect timeout=10)'))', 尝试退回常规的requests请求
2024-02-13 21:42:07 core.func:79 DEBUG: 移除标题尾部的女优名: '嫉妬沉迷於女僕的男友…過激女僕裝扮全力乳交的女友' [ 安達夕莉]
2024-02-13 21:42:07 main:187 DEBUG: 从'airav'中获取了字段: actress cover genre plot preview_pics producer publish_date title url
2024-02-13 21:42:07 core.file:194 DEBUG: 目标路径不是远程文件系统
2024-02-13 21:42:08 main:526 DEBUG: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 410, in increment
  File "urllib3\packages\six.py", line 734, in reraise
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JavSP.py", line 518, in download_cover
  File "web\base.py", line 219, in download
  File "web\base.py", line 185, in urlretrieve
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-02-13 21:42:08 main:526 DEBUG: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 410, in increment
  File "urllib3\packages\six.py", line 734, in reraise
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JavSP.py", line 518, in download_cover
  File "web\base.py", line 219, in download
  File "web\base.py", line 185, in urlretrieve
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-02-13 21:42:08 main:526 DEBUG: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 410, in increment
  File "urllib3\packages\six.py", line 734, in reraise
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 362, in connect
  File "urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JavSP.py", line 518, in download_cover
  File "web\base.py", line 219, in download
  File "web\base.py", line 185, in urlretrieve
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-02-13 21:42:08 main:527 ERROR: 下载封面图片失败
2024-02-13 21:42:08 main:528 DEBUG: big_covers:[], covers['https://wiki-img.airav.wiki/storage/big_pic/272411.jpg']
2024-02-13 21:42:08 main:488 DEBUG: 下载封面图片失败
Traceback (most recent call last):
  File "JavSP.py", line 445, in RunNormalMode
  File "JavSP.py", line 410, in check_step
Exception: 下载封面图片失败

2024-02-13 21:42:08 main:489 ERROR: 整理失败: 下载封面图片失败

2024-02-13 21:42:14 main:96 DEBUG: web.javlib: 网络错误，正在重试 (2/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102FEFA0>, 'Connection to www.javlibrary.com timed out. (connect timeout=10)'))"))
2024-02-13 21:42:24 web.base:57 DEBUG: 无法通过CloudFlare检测: 'HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102E67C0>, 'Connection to www.javlibrary.com timed out. (connect timeout=10)'))', 尝试退回常规的requests请求
2024-02-13 21:42:34 main:96 DEBUG: web.javlib: 网络错误，正在重试 (3/3): 
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=SSIS-957 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024A102ECB80>, 'Connection to www.javlibrary.com timed out. (connect timeout=10)'))"))
```

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by Yuukiy** [comment]
在配置文件里设置一下代理吧，现在不挂代理基本不能用了
