### ISSUE TITLE
Fanza无法刮削部分CID信息，但fanza网页是可以搜索到此CID信息

### ISSUE THREAD

**Issue by TENTLONG** [Yuukiy/JavSP#215]
### 问题详情

2024-02-15 14:38:07 main:558 DEBUG: =========================JavSP v1.7=========================
2024-02-15 14:38:09 core.file:145 DEBUG: 影片数据源类型: 145tb017: cid
2024-02-15 14:38:09 main:579 INFO: 扫描影片文件：共找到 1 部影片
2024-02-15 14:38:09 main:418 INFO: 正在整理: 145tb017.mp4
2024-02-15 14:38:11 main:87 DEBUG: web.fanza: 未找到影片: 'None'
2024-02-15 14:38:11 main:134 DEBUG: 自动更正影片数据源类型: tb-017 (145tb017): normal
2024-02-15 14:38:11 main:488 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 424, in RunNormalMode
  File "JavSP.py", line 410, in check_step
Exception: 为其配置的1个抓取器均未获取到影片信息

2024-02-15 14:38:11 main:489 ERROR: 整理失败: 为其配置的1个抓取器均未获取到影片信息

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by TENTLONG** [comment]
JAV321可识别到，但会默认进行改名，会和其余CID改名后重名，出现异常
