### ISSUE TITLE
爬取jav321失败

### ISSUE THREAD

**Issue by glyh** [Yuukiy/JavSP#293]
### 问题详情

爬虫测试数据的所有爬取jav321的请求现在都失败了

### 运行方式

我是从源代码运行的

### 代理

是

### 日志

2024-04-21 05:58:26 __main__:112 ERROR: __main__: 未找到影片: 'SCUTE-1177'
Traceback (most recent call last):
  File "/home/javsp/Documents/self-hosted/Jellyfin/tools/JavSPn/javspn/web/./jav321.py", line 109, in <module>
    parse_data(movie)
  File "/home/javsp/Documents/self-hosted/Jellyfin/tools/JavSPn/javspn/web/./jav321.py", line 37, in parse_data
    raise MovieNotFoundError(__name__, movie.dvdid)
javspn.web.exceptions.MovieNotFoundError: __main__: 未找到影片: 'SCUTE-1177'

### HTTP响应

网页返回源码200
```html
<html lang="ja">\n<head>\n<meta http-equiv="X-UA-Compatible" content="IE=edge"/>\n<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>\n<meta name="viewport" content="width=device-width, initial-scale=1.0"/>\n<meta name="applicable-device" content="pc,mobile"/>\n<link rel="icon" type="image/png" href="data:;base64,iVBORw0KGgo="/>\n<link rel="icon" href="data:;base64,="/>\n<link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"/>\n<meta name="trafficjunky-site-verification" content="5t6vrynq8"/>\n<meta name="propeller" content="8c982135933fddb9bda37f7341f8d456"/>\n<meta name="ero_verify" content="2872ecd468361b6ebb461a9801270b07"/>\n<title>JAV321 dmm</title>\n<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>\n<link href="https://vjs.zencdn.net/5.8.8/video-js.css" rel="stylesheet"/>\n<script src="https://code.jquery.com/jquery-1.12.4.min.js"/>\n<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"/>\n<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"/>\n<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js"/>\n<script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"/>\n<script src="https://vjs.zencdn.net/5.8.8/video.js"/>\n<meta name="juicyads-site-verification" content="261f9ab1f219661ed9038571027b3f7c"/>\n</head>\n<body>\n<script>\n(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){\n (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');\nga(\'create\', \'UA-17088225-8\', \'auto\');\nga(\'send\', \'pageview\');\n</script>\n<div class="row"><div class="col-md-10 col-md-offset-1 col-xs-12">\n<nav class="navbar navbar-default" role="navigation">\n\t<div class="container-fluid">\n\t\t<div class="navbar-header ">\n\t\t\t<a class="navbar-brand" href="https://www.jav321.com/">JAV321</a> <a class="navbar-brand" href="https://www.jav321.com/best_seller/1/2024/1">AV</a> <a class="navbar-brand" href="https://www.jav321.com/best_seller/2/2021/1">&#32032;&#20154;</a> <a class="navbar-brand" href="https://www.jav321.com/series_title_list/1">&#12471;&#12522;&#12540;&#12474;</a> <a class="navbar-brand" href="https://www.jav321.com/genre_list">&#12472;&#12515;&#12531;&#12523;</a>\n\t\t</div>\n<!--\n\t\t<ul class="nav navbar-nav ">\n\t\t\t<li><a href="/play_list/1">Play List</a></li>\n\t\t\t<li><a href="/best_seller/1/2017/1">AV</a> <a href="/best_seller/2/2017/1">&#32032;&#20154;</a> <a href="/series_title_list/1">&#12471;&#12522;&#12540;&#12474;</a> <a href="/genre_list">&#12472;&#12515;&#12531;&#12523;</a> <a href="/discuz/forum.php"></a></li>\n\t\t\t<li><a href="/best_seller/2/2017/1">&#32032;&#20154;</a></li>\n\t\t\t<li><a href="/series_title_list/1">&#12471;&#12522;&#12540;&#12474;</a></li>\n\t\t\t<li><a href="/genre_list">&#12472;&#12515;&#12531;&#12523;</a></li>\n\t\t</ul>\n-->\n\t\t<form class="navbar-form navbar-left" role="search" action="https://www.jav321.com/search" method="POST">\n\t\t\t<div class="form-group input-group">\n\t\t\t\t<input type="text" name="sn" class="form-control" placeholder="&#21697;&#30058;" size="10"/>\n\t\t\t\t<span class="input-group-btn"><button type="submit" class="btn btn-default">Search</button></span>\n\t
\t\t</div>\n\t\t</form>\n\t\t<form class="navbar-form navbar-left hidden-xs" role="search" action="https://www.jav321.com/emule" method="POST">\n\t\t\t<div class="form-group input-group">\n\t\t\t\t<input type="text" name="kw" class="form-control" placeholder="" size="10"/>\n\t\t\t<span class="input-group-btn"><button type="submit" class="btn btn-default">Download</button></span>\n\t\t\t</div>\n\t\t</form>\n\t\t<div class="btn-group navbar-right hidden-xs">\n\t\t\t<button type="button" class="btn btn-default dropdown-toggle navbar-btn" data-toggle="dropdown">\n\t\t\t\tLanguage <span class="caret"/>\n\t\t\t</button>\n\t\t\t<ul class="dropdown-menu" role="menu">\n\t\t\t\t<li><a href="https://en.jav321.com/search" target="_self">English</a></li>\n\t\t\t\t<li><a href="https://jp.jav321.com/search" target="_self">&#26085;&#26412;&#35486;</a></li>\n\t\t\t\t<li><a href="https://tw.jav321.com/search" target="_self">&#27491;&#39636;&#20013;&#25991;</a></li>\n\t\t\t\t<li><a href="https://www.jav321.com/search" target="_self">&#31616;&#20307;&#20013;&#25991;</a></li>\n\t\t\t</ul>\n\t\t</div>\n\t</div>\n</nav>\n</div></div>\n<div class="row"><div class="col-md-10 col-md-offset-1 col-xs-10"><div class="alert alert-danger" role="alert">AV&#12364;&#35211;&#12388;&#12363;&#12426;&#12414;&#12379;&#12435;&#12391;&#12375;&#12383;&#12290;</div></div></div><script> \nvar interval = setInterval(function(){\n\t$("img").lazyload();\n\tclearInterval(interval);\n},1000);\n$(function() { \n\t$("img").lazyload(); \n\teffect : "fadeIn";\n\n}); \nthis.top.location !== this.location &amp;&amp; (this.top.location = this.location);\n</script>\n</body></html>
```
但应该是302

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by glyh** [comment]
https://github.com/glyh/JavSPn/actions/runs/8765762950/job/24057098152

**Comment by glyh** [comment]
好像是我的fork里面重写网络请求模块引入的bug
