### ISSUE TITLE
没有封面的内容只制作nfo

### ISSUE THREAD

**Issue by maodun96** [Yuukiy/JavSP#316]
### 功能建议

希望能在手动模式增加“没有封面的内容只制作nfo”的选择，因为有些fc2内容就是在这几个站没有封面，想办法谷歌找下还是能找到。

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
这个就没必要了，在搜索引擎找都费劲的用程序处理比较困难，建议你手动收集。
nfo只是一种特定格式的媒体信息文件，你可以使用文本编辑器修改，包括封面和海报也都只是特定的文件名。
下面是一些信息，你可以通过他们学习制作。
https://kodi.wiki/view/Artwork_types
https://kodi.wiki/view/NFO_files
https://kodi.wiki/view/NFO_files/Movies
https://emby.media/support/articles/Metadata-manager.html?q=nfo
https://gist.github.com/CosimoVestri/9cb96440273063ce0e3a614bf8965e2e

**Comment by maodun96** [comment]
> 这个就没必要了，在搜索引擎找都费劲的用程序处理比较困难，建议你手动收集。 nfo只是一种特定格式的媒体信息文件，你可以使用文本编辑器修改，包括封面和海报也都只是特定的文件名。 下面是一些信息，你可以通过他们学习制作。 https://kodi.wiki/view/Artwork_types https://kodi.wiki/view/NFO_files https://kodi.wiki/view/NFO_files/Movies https://emby.media/support/articles/Metadata-manager.html?q=nfo https://gist.github.com/CosimoVestri/9cb96440273063ce0e3a614bf8965e2e

我的意思是 只有图片搜索不到，比如说某些片子下架后很快下架了。索引网站就会只收录文字信息而没有收录到图片信息。这种情况如果能导出nfo，自己配图这样速度会快很多。

不过还是谢谢老哥的教程地址。

**Comment by musnow** [comment]
如果是已经有模块的网站，你可以试着把`config.ini`里面`required_keys`的`cover`字段移除，这样程序应该不会报错，最终保留刮削结果。

**Comment by maodun96** [comment]
> 如果是已经有模块的网站，你可以试着把`config.ini`里面`required_keys`的`cover`字段移除，这样程序应该不会报错，最终保留刮削结果。

尝试过了的，只保留
required_keys = title


log：
2024-06-03 15:28:58 core.file:145 DEBUG: 影片数据源类型: FC2-1143740: fc2
2024-06-03 15:28:58 main:587 INFO: 扫描影片文件：共找到 1 部影片
2024-06-03 15:28:58 main:426 INFO: 正在整理: FC2-PPV-1143740.mp4
2024-06-03 15:28:58 main:81 DEBUG: web.msin: 抓取成功: 'FC2-1143740': 'https://db.msin.jp/page/movie?id=2224'
2024-06-03 15:28:58 main:87 DEBUG: web.javdb: 未找到影片: 'FC2-1143740'
2024-06-03 15:28:59 main:87 DEBUG: web.javmenu: 未找到影片: 'FC2-1143740'
2024-06-03 15:28:59 main:87 DEBUG: web.avsox: 未找到影片: 'FC2-1143740'
2024-06-03 15:28:59 main:87 DEBUG: web.fc2: 未找到影片: 'FC2-1143740'
2024-06-03 15:28:59 main:187 DEBUG: 从'msin'中获取了字段: duration producer publish_date title url
2024-06-03 15:28:59 core.file:200 DEBUG: 目标路径是远程文件系统
2024-06-03 15:28:59 main:535 ERROR: 下载封面图片失败
2024-06-03 15:28:59 main:536 DEBUG: big_covers:[], covers[]
2024-06-03 15:28:59 main:496 DEBUG: 下载封面图片失败
Traceback (most recent call last):
  File "JavSP.py", line 453, in RunNormalMode
  File "JavSP.py", line 418, in check_step
Exception: 下载封面图片失败

程序应该是把封面图片作为默认的条件

**Comment by musnow** [comment]
你可以拉取项目，将`JavSP.py`从502行到529行注释掉就可以得到你想要的效果了。

**Comment by zymshirley** [comment]
> 你可以拉取项目，将`JavSP.py`从502行到529行注释掉就可以得到你想要的效果了。

源代码运行，不是Source code，源代码里没有JavSP.py，只有个__main__.py是类似的，怎么修改呢，不要下载任何图片，只抓取nfo
