### ISSUE TITLE
封面下载失败的原因是什么？？

### ISSUE THREAD

**Issue by c2592244938** [Yuukiy/JavSP#317]
### 问题详情

2024-06-03 20:57:48 core.func:79 DEBUG: 移除标题尾部的女优名: '被想當內衣模特兒的婆婆豔麗肉體引誘…隨著本能持續沉溺的1週間' [ 大石紗季]
2024-06-03 20:57:48 main:187 DEBUG: 从'airav'中获取了字段: actress cover genre plot preview_pics preview_video producer publish_date title url
2024-06-03 20:57:51 core.image:19 DEBUG: cannot identify image file '#整理完成\\大石紗季\\[ROE-211-C] 被想当内衣模特儿的婆婆艳丽肉体引诱…随着本能持续沉溺的1周间\\fanart.jpg'
Traceback (most recent call last):
  File "core\image.py", line 15, in valid_pic
  File "PIL\Image.py", line 3309, in open
PIL.UnidentifiedImageError: cannot identify image file '#整理完成\\大石紗季\\[ROE-211-C] 被想当内衣模特儿的婆婆艳丽肉体引诱…随着本能持续沉溺的1周间\\fanart.jpg'
2024-06-03 20:57:51 main:531 DEBUG: 图片无效或已损坏: 'https://wiki-img.airav.wiki/storage/big_pic/278887.jpg'，尝试更换下载地址

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 日志

[JavSP.log](https://github.com/user-attachments/files/15534148/JavSP.log)

### 运行截图（可选）

![屏幕截图 2024-06-03 210407](https://github.com/Yuukiy/JavSP/assets/110923733/940319a3-67e2-485a-a15f-9aeeb892bf92)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
你的本地网络访问受限，建议设置代理。

**Comment by c2592244938** [comment]
指条路，代理怎么挂
