### ISSUE TITLE
建議增加https://www.arzon.jp/的資料刮削

### ISSUE THREAD

**Issue by boringboringman** [Yuukiy/JavSP#337]
### 功能建议

先感謝大大不斷的更新這個十分有用的工具
請問會否考慮增加對IV (image video)的刮削支持呢? IV其實都佔據一席位亦需要整體管理
參考前大大製作的EverAver Renamer 也有用到 arzon 去刮削, 關於有碼片, IV片資料亦頗齊全

如SHMO-031 是鈴木心春的作品Spring has come 2
https://www.arzon.jp/image_1176276.html

如JAVSP能支持IV的刮削真是對一眾IV收藏者的裨益, 先行感謝

### 提交须知

- [X] 我确认使用的是最新版本并且已经阅读过Wiki帮助文档

**Comment by musnow** [comment]
同 #310
如果可行，建议pr

**Comment by musnow** [comment]
你可以拉取下面这个分支，然后在配置文件内添加arzon模块即可使用。
https://github.com/musnow/JavSP

**Comment by boringboringman** [comment]
感謝你的回覆, 但小弟不才, 只懂用.exe版面的JAVSP
未攪清楚如果運行分支及添加模塊 明明有arzon的模塊在面前卻用不到

**Comment by boringboringman** [comment]
> 你可以拉取下面这个分支，然后在配置文件内添加arzon模块即可使用。 https://github.com/musnow/JavSP

咸濕是最大的學習動力, 好不容易已經找到方法行你的版本JavSP.py 找取一般迷片是沒有問題的
config.ini 內已直接指定arzon 仍未能找取到任何, 繼續以SHMO-031為例, 不知是否"添加arzon模塊"時出錯

[CrawlerSelect]
normal = arzon


2024-07-13 16:36:34 main:648 DEBUG: ======================JavSP 未知版本/从代码运行======================
2024-07-13 16:36:37 main:82 WARNING: 配置的抓取器无效: javdb
2024-07-13 16:36:37 core.file:147 DEBUG: 影片数据源类型: SHMO-031: normal
2024-07-13 16:36:37 main:673 INFO: 扫描影片文件：共找到 1 部影片
2024-07-13 16:36:37 main:480 INFO: 正在整理: arzon SHMO-031 鈴木心春 -  Spring has come 2～春色気分～[SHMO-031].mkv
2024-07-13 16:36:45 main:102 DEBUG: web.arzon: 未找到影片: 'SHMO-031'
2024-07-13 16:36:45 main:551 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "E:\JavSP-master\JavSP.py", line 486, in RunNormalMode
    check_step(all_info, msg)
  File "E:\JavSP-master\JavSP.py", line 471, in check_step
    raise Exception(msg + '\n')
Exception: 为其配置的1个抓取器均未获取到影片信息

2024-07-13 16:36:45 main:552 ERROR: 整理失败: 为其配置的1个抓取器均未获取到影片信息

**Comment by musnow** [comment]
看了一下，元素和av的有些许不同，和上面一样你可以使用[arzon_iv](https://github.com/musnow/JavSP/blob/master/web/arzon_iv.py)模块，但不应该是这样的整理模式。

**Comment by boringboringman** [comment]
> 看了一下，元素和av的有些许不同，和上面一样你可以使用[arzon_iv](https://github.com/musnow/JavSP/blob/master/web/arzon_iv.py)模块，但不应该是这样的整理模式。


感激迅速的回覆, 試了arzon_iv 是可以找到SHMO-031的資訊但最後下載封面時失敗了
config.ini
[CrawlerSelect]
normal = arzon_iv


2024-07-13 17:11:09 main:648 DEBUG: ======================JavSP 未知版本/从代码运行======================
2024-07-13 17:11:16 main:82 WARNING: 配置的抓取器无效: javdb
2024-07-13 17:11:16 core.file:147 DEBUG: 影片数据源类型: SHMO-031: normal
2024-07-13 17:11:16 main:673 INFO: 扫描影片文件：共找到 1 部影片
2024-07-13 17:11:16 main:480 INFO: 正在整理: SHMO-031.mkv
2024-07-13 17:11:22 main:96 DEBUG: web.arzon_iv: 抓取成功: 'SHMO-031': 'https://www.arzon.jp/image_1176276.html'
2024-07-13 17:11:22 main:202 DEBUG: 从'arzon_iv'中获取了字段: actress cover duration genre plot producer publish_date title url
2024-07-13 17:11:22 core.file:213 DEBUG: 目标路径是远程文件系统
2024-07-13 17:11:22 core.image:19 DEBUG: cannot identify image file '\\\\javspSTATION\\FTP_Upload\\TEST\\#整理完成\\打碼情況未知\\[SHMO-031] 鈴木心春 - Spring has come 2 鈴木心春 [オルスタックソフト販売][2014-03-28]\\SHMO-031-fanart.jpg'
Traceback (most recent call last):
  File "E:\JavSP-master\core\image.py", line 15, in valid_pic
    img = ImageOps.exif_transpose(Image.open(pic_path))
  File "C:\Users\myk17\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '\\\\javspSTATION\\FTP_Upload\\TEST\\#整理完成\\打碼情況未知\\[SHMO-031] 鈴木心春 - Spring has come 2 鈴木心春 [オルスタックソフト販売][2014-03-28]\\SHMO-031-fanart.jpg'
2024-07-13 17:11:22 main:587 DEBUG: 图片无效或已损坏: 'https://img.arzon.jp/image/7/1176/1176276L.jpg'，尝试更换下载地址
2024-07-13 17:11:22 main:591 ERROR: 下载封面图片失败
2024-07-13 17:11:22 main:592 DEBUG: big_covers:[], covers['https://img.arzon.jp/image/7/1176/1176276L.jpg']
2024-07-13 17:11:22 main:551 DEBUG: 下载封面图片失败
Traceback (most recent call last):
  File "E:\JavSP-master\JavSP.py", line 507, in RunNormalMode
    check_step(cover_dl, '下载封面图片失败')
  File "E:\JavSP-master\JavSP.py", line 471, in check_step
    raise Exception(msg + '\n')
Exception: 下载封面图片失败

2024-07-13 17:11:22 main:552 ERROR: 整理失败: 下载封面图片失败

**Comment by musnow** [comment]
将web->base.py的24行改成下面内容可以暂时解决这个问题。
`headers = {'Referer':'https://www.arzon.jp/','User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0'}
`

**Comment by boringboringman** [comment]
> 将web->base.py的24行改成下面内容可以暂时解决这个问题。你可以直接用git拉取，应该就可以了 `headers = {'Referer':'https://www.arzon.jp/','User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0'} `

見到它能運行到下載封面的時間實在興奮, 可是最後不知如何還是失敗

2024-07-13 17:44:15 main:648 DEBUG: ======================JavSP 未知版本/从代码运行======================
2024-07-13 17:44:25 main:82 WARNING: 配置的抓取器无效: javdb
2024-07-13 17:44:25 core.file:147 DEBUG: 影片数据源类型: SHMO-031: normal
2024-07-13 17:44:25 main:673 INFO: 扫描影片文件：共找到 1 部影片
2024-07-13 17:44:25 main:480 INFO: 正在整理: SHMO-031.mkv
2024-07-13 17:44:30 main:96 DEBUG: web.arzon_iv: 抓取成功: 'SHMO-031': 'https://www.arzon.jp/image_1176276.html'
2024-07-13 17:44:30 main:202 DEBUG: 从'arzon_iv'中获取了字段: actress cover duration genre plot producer publish_date title url
2024-07-13 17:44:30 core.file:213 DEBUG: 目标路径是远程文件系统
2024-07-13 17:44:32 main:584 DEBUG: 已下载封面: 'https://img.arzon.jp/image/7/1176/1176276L.jpg'
2024-07-13 17:44:32 main:551 DEBUG: bad argument type: NoneType(None)
Traceback (most recent call last):
  File "E:\JavSP-master\JavSP.py", line 537, in RunNormalMode
    write_nfo(movie.info, movie.nfo_file)
  File "E:\JavSP-master\core\nfo.py", line 62, in write_nfo
    nfo.append(E.genre(i))
  File "src\lxml\builder.py", line 220, in lxml.builder.ElementMaker.__call__
TypeError: bad argument type: NoneType(None)
2024-07-13 17:44:32 main:552 ERROR: 整理失败: bad argument type: NoneType(None)
2024-07-13 17:45:44 main:648 DEBUG: ======================JavSP 未知版本/从代码运行======================
2024-07-13 17:45:47 main:82 WARNING: 配置的抓取器无效: javdb
2024-07-13 17:45:47 core.file:147 DEBUG: 影片数据源类型: SHMO-031: normal
2024-07-13 17:45:47 main:673 INFO: 扫描影片文件：共找到 1 部影片
2024-07-13 17:45:47 main:480 INFO: 正在整理: SHMO-031.mkv
2024-07-13 17:45:53 main:96 DEBUG: web.arzon_iv: 抓取成功: 'SHMO-031': 'https://www.arzon.jp/image_1176276.html'
2024-07-13 17:45:53 main:202 DEBUG: 从'arzon_iv'中获取了字段: actress cover duration genre plot producer publish_date title url
2024-07-13 17:45:53 core.file:213 DEBUG: 目标路径是远程文件系统
2024-07-13 17:45:54 main:584 DEBUG: 已下载封面: 'https://img.arzon.jp/image/7/1176/1176276L.jpg'
2024-07-13 17:45:54 main:551 DEBUG: bad argument type: NoneType(None)
Traceback (most recent call last):
  File "E:\JavSP-master\JavSP.py", line 537, in RunNormalMode
    write_nfo(movie.info, movie.nfo_file)
  File "E:\JavSP-master\core\nfo.py", line 62, in write_nfo
    nfo.append(E.genre(i))
  File "src\lxml\builder.py", line 220, in lxml.builder.ElementMaker.__call__
TypeError: bad argument type: NoneType(None)
2024-07-13 17:45:54 main:552 ERROR: 整理失败: bad argument type: NoneType(None)
2024-07-13 17:47:49 main:648 DEBUG: ======================JavSP 未知版本/从代码运行======================
2024-07-13 17:47:52 main:82 WARNING: 配置的抓取器无效: javdb
2024-07-13 17:47:52 core.file:147 DEBUG: 影片数据源类型: SHMO-031: normal
2024-07-13 17:47:52 main:673 INFO: 扫描影片文件：共找到 1 部影片
2024-07-13 17:47:52 main:480 INFO: 正在整理: SHMO-031.mkv
2024-07-13 17:47:57 main:96 DEBUG: web.arzon_iv: 抓取成功: 'SHMO-031': 'https://www.arzon.jp/image_1176276.html'
2024-07-13 17:47:57 main:202 DEBUG: 从'arzon_iv'中获取了字段: actress cover duration genre plot producer publish_date title url
2024-07-13 17:47:57 core.file:213 DEBUG: 目标路径是远程文件系统
2024-07-13 17:47:58 main:584 DEBUG: 已下载封面: 'https://img.arzon.jp/image/7/1176/1176276L.jpg'
2024-07-13 17:47:58 main:551 DEBUG: bad argument type: NoneType(None)
Traceback (most recent call last):
  File "E:\JavSP-master\JavSP.py", line 537, in RunNormalMode
    write_nfo(movie.info, movie.nfo_file)
  File "E:\JavSP-master\core\nfo.py", line 62, in write_nfo
    nfo.append(E.genre(i))
  File "src\lxml\builder.py", line 220, in lxml.builder.ElementMaker.__call__
TypeError: bad argument type: NoneType(None)
2024-07-13 17:47:58 main:552 ERROR: 整理失败: bad argument type: NoneType(None)

**Comment by musnow** [comment]
你可以直接用git pull拉取，现在应该是可以运行的状态，如果你想手动修改arzon_iv.py参考下面的链接73-77行。
https://github.com/musnow/JavSP/blob/master/web/arzon_iv.pyL73

**Comment by boringboringman** [comment]
> musnow

實在是大感謝 可以用到啦 
急不及待給它運行一次IV 資料夾!

**Comment by glyh** [comment]
https://github.com/Yuukiy/JavSP/pull/377
