### ISSUE TITLE
无法识别到IKUNA 即使我已经增加了;IKUNA-\d+ 在ini文件中, 还是无法识别.

### ISSUE THREAD

**Issue by lucky9peach** [Yuukiy/JavSP#344]
### 问题详情

无法识别到IKUNA 即使我已经增加了;IKUNA-\d+ 在ini文件中, 还是无法识别.

### 运行方式

我是从源代码运行的

### 代理

否

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档

**Comment by musnow** [comment]
文件命名不规范，使用类似“IKUNA-001.mp4”的文件名

**Comment by lucky9peach** [comment]
我的文件名是IKUNA-012.mp4 依旧无法识别

**Comment by musnow** [comment]
上传日志

**Comment by lucky9peach** [comment]
2024-07-20 22:57:39 main:426 INFO: 正在整理: hhd800.com@IKUNA-012.mp4
2024-07-20 22:57:39 main:87 DEBUG: web.javdb: 未找到影片: 'IKUNA-012'
2024-07-20 22:57:40 main:81 DEBUG: web.javbus: 抓取成功: 'IKUNA-012': 'https://www.javbus.com/IKUNA-012'
2024-07-20 22:57:40 main:187 DEBUG: 从'javbus'中获取了字段: actress actress_pics cover director duration genre genre_id preview_pics producer publish_date publisher serial title uncensored url
2024-07-20 22:57:40 core.image:19 DEBUG: cannot identify image file '#整理完成\\2024-08-02\\[IKUNA-012] 『IKUNA＃1.60』友田彩也香vs波多野結衣 全セクシー界GAMANKO最侠対決 アへアクメ超セクシー級「最侠」頂上決戦！ いつもイキ潮まくるAVスター競演＜イキガマン狂い＞絶頂決戦『IKUNA』シーズン4！イキガマンの果てに手にする絶頂は恍惚か！失神か！失禁か！最高の絶頂女王…\\IKUNA-012-fanart.jpg'
Traceback (most recent call last):
  File "core\image.py", line 15, in valid_pic
  File "PIL\Image.py", line 3309, in open
PIL.UnidentifiedImageError: cannot identify image file '#整理完成\\2024-08-02\\[IKUNA-012] 『IKUNA＃1.60』友田彩也香vs波多野結衣 全セクシー界GAMANKO最侠対決 アへアクメ超セクシー級「最侠」頂上決戦！ いつもイキ潮まくるAVスター競演＜イキガマン狂い＞絶頂決戦『IKUNA』シーズン4！イキガマンの果てに手にする絶頂は恍惚か！失神か！失禁か！最高の絶頂女王…\\IKUNA-012-fanart.jpg'
2024-07-20 22:57:40 main:531 DEBUG: 图片无效或已损坏: 'https://www.javbus.com/pics/cover/aos2_b.jpg'，尝试更换下载地址
2024-07-20 22:57:40 main:535 ERROR: 下载封面图片失败
2024-07-20 22:57:40 main:536 DEBUG: big_covers:[], covers['https://www.javbus.com/pics/cover/aos2_b.jpg']
2024-07-20 22:57:40 main:496 DEBUG: 下载封面图片失败
Traceback (most recent call last):
  File "JavSP.py", line 453, in RunNormalMode
  File "JavSP.py", line 418, in check_step
Exception: 下载封面图片失败


2024-07-20 23:02:23 main:566 DEBUG: ========================JavSP v1.7.3========================
2024-07-20 23:02:25 core.file:59 ERROR: 无法提取影片番号: 'C:\剪辑完成\IKUNA-012.mp4'
2024-07-20 23:02:25 main:543 ERROR: 未找到影片文件
2024-07-20 23:04:35 main:566 DEBUG: ========================JavSP v1.7.3========================
2024-07-20 23:04:37 core.file:59 ERROR: 无法提取影片番号: 'C:\剪辑完成\IKUNA-012.mp4'
2024-07-20 23:04:37 main:543 ERROR: 未找到影片文件

**Comment by musnow** [comment]
这不是已经刮削了吗，只是没下载封面，你在配置文件改了什么导致的无法匹配

**Comment by lucky9peach** [comment]
我改了文件名 然后文件夹是空的 没有复制进去 也没有修改文件名 没有生成nfo文件
修改文件名之后无法识别
自己添加了ini 还是没法识别 已经又重置回去了
每次到IKUNA的都这个问题

**Comment by musnow** [comment]
你的网络问题，去掉javbus这个模块试试

**Comment by lucky9peach** [comment]
我人在国外 没有被屏蔽 千兆上下行 真的上次也是另一部IKUNA不行

**Comment by musnow** [comment]
。。。。为什么喜欢犟，你获取的封面地址有问题，你在月球也没用啊，两个地址你看看有什么区别，去掉模块再试一下，没必要非要用一个网站。把配置和日志一块上传上来我看看
https://www.javbus.com/pics/cover/aos2_b.jpg
https://www.busdmm.shop/pics/cover/aos2_b.jpg

**Comment by lucky9peach** [comment]
==============================================
   Jav Scraper Package: v1.7.3 (已是最新版)
==============================================

请选择要整理的文件夹：C:\剪辑完成
扫描影片文件...
无法提取影片番号: 'C:\剪辑完成\IKUNA-012.mp4'
未找到影片文件
请按任意键继续. . .

去掉javbus了已经 用的db
原版软件
已经不提取了
难道要把已经提取过的log删掉?
我刮削在win系统的NAS上 远程过去的 拷文件很麻烦

**Comment by musnow** [comment]
> 这不是已经刮削了吗，只是没下载封面，你在配置文件改了什么导致的无法匹配

配置文件，改了什么？沟通这么困难吗

**Comment by lucky9peach** [comment]
我说了原版软件 没有任何修改
而且多试了你说的去掉javbus 只留下了javdb

**Comment by musnow** [comment]
> 无法识别到IKUNA 即使我已经增加了;IKUNA-\d+ 在ini文件中, 还是无法识别.

`;IKUNA-\d+`加在了哪里，或者你重新下载一份配置文件放进去
https://github.com/Yuukiy/JavSP/blob/master/core/config.ini

**Comment by Yuukiy** [comment]
未复现
![image](https://github.com/user-attachments/assets/6612ec3d-d434-4be5-bbae-f6f157e84156)
并且合理推测，你改了配置文件，改错了
```
# 要忽略的正则表达式（如果你不熟悉正则表达式，请不要修改此配置，否则可能严重影响番号识别效果）
ignore_regex = \w+2048\.com;Carib(beancom)?;[^a-z\d](f?hd|lt)[^a-z\d];IKUNA-\d+
```
> **要忽略的正则表达式（如果你不熟悉正则表达式，请不要修改此配置，否则可能严重影响番号识别效果）**
