### ISSUE TITLE
在使用 Alist+rclone 挂载的本地目录进行刮削时无法识别文件

### ISSUE THREAD

**Issue by libratechie** [Yuukiy/JavSP#388]
### 环境信息：
- JavSP版本: v1.8
- Python版本: 3.12.6
- 挂载方式: 使用Alist+rclone将网盘挂载至本地目录

### 问题描述

在使用 Alist+rclone 挂载的本地目录进行刮削时，遇到了以下错误：

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core\image.py", line 16, in valid_pic
  File "PIL\Image.py", line 3274, in open
  File "ntpath.py", line 651, in realpath
  File "ntpath.py", line 601, in _getfinalpathname_nonstrict
OSError: [WinError 1005] 此卷不包含可识别的文件系统。

请确定所有请求的文件系统驱动程序已加载，且此卷未损坏。: 'C:\\Alist\\挂载\\成人\\刮削仓库\\#整理完成\\JUL-700-C\\fanart.jpg'
Arguments: 
  '此卷不包含可识别的文件系统。\r\n请确定所有请求的文件系统驱动程序已加载，且此卷未损坏。'
2024-09-28 19:30:09 main:567 DEBUG: 图片无效或已损坏: 'https://c0.jdbstatic.com/covers/mw/Mwyw7.jpg'，尝试更换下载地址
2024-09-28 19:30:09 main:571 ERROR: 下载封面图片失败
2024-09-28 19:30:09 main:572 DEBUG: big_covers:[], covers['https://www.seedmm.help/pics/cover/8fc8_b.jpg', 'https://pics.dmm.co.jp/mono/movie/adult/jul700/jul700pl.jpg', 'http://pics.dmm.co.jp/digital/video/jul00700/jul00700pl.jpg', 'https://c0.jdbstatic.com/covers/mw/Mwyw7.jpg']
2024-09-28 19:30:09 main:532 DEBUG: 下载封面图片失败
Traceback (most recent call last):
  File "JavSP.py", line 488, in RunNormalMode
  File "JavSP.py", line 452, in check_step
Exception: 下载封面图片失败

2024-09-28 19:30:09 main:533 ERROR: 整理失败: 下载封面图片失败
```

### 最终结果

尽管报错信息表明无法识别挂载的文件系统，但实际上刮削数据似乎部分成功。在“#整理完成”目录中已经生成了对应的文件夹，并且 fanart.jpg 文件已经保存。然而，nfo 文件和 poster.jpg 文件未生成。

![Snipaste_2024-09-28_19-31-00](https://github.com/user-attachments/assets/b1c8c532-9966-4090-ad22-3869690e5083)

该问题似乎是在 v1.8 版本中出现的，因为在回退到 v1.7.3 版本时，刮削功能能够正常工作。这让我怀疑新版本是否移除了对通过挂载目录进行刮削的支持，或者是否存在未兼容的问题。

![image](https://github.com/user-attachments/assets/d3c9de9f-6b75-4b72-98a3-494b78ca1b76)

### 期望的行为：

- 希望能够确认该问题是否是 v1.8 版本中的 Bug。
- 期待获得关于挂载文件系统刮削支持是否被移除或修改的信息。

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

[JavSP.log](https://github.com/user-attachments/files/17174222/JavSP.log)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by chanho0** [comment]
同样情况，可复现

**Comment by libratechie** [comment]
同意可能是底层文件系统不兼容导致，也可能涉及到Alist，将不在此讨论；
我通过批量创建 strm 文件映射视频流来规避该问题，不影响刮削和 emby 的播放，如果有相同问题的可以尝试使用 strm 来解决该问题。
