### ISSUE TITLE
javdb的部分内容好像获取不了....

### ISSUE THREAD

**Issue by chenova** [Yuukiy/JavSP#4]
Crawler: web.jav321: SIMM-415: 未处理的异常: list index out of range
Traceback (most recent call last):
  File "JavSP.py", line 78, in wrapper
  File "web\jav321.py", line 63, in parse_data
IndexError: list index out of range
所有爬虫均未获取到字段: 'cover'，抓取失败
整理失败

config里删去获取cover后，又显示获取gener失败...

**Comment by chenova** [comment]
好像是config里设置的部分字段获取问题，我单独找了部影片获取

2021-04-27 02:01:23 main DEBUG: 由于未配置有效的fc2fan路径，已跳过该抓取器
2021-04-27 02:01:23 core.file DEBUG: 影片数据源类型: SIMM-542: normal
2021-04-27 02:01:23 main INFO: 扫描影片文件：共找到 1 部影片
2021-04-27 02:01:23 main INFO: 正在整理: 345SIMM-542.mp4
2021-04-27 02:01:23 main DEBUG: Crawler: web.javdb: SIMM-542: 网络错误，正在重试 (1/3): 
403 Client Error: Forbidden for url: https://www.javdb.com/search?q=SIMM-542
2021-04-27 02:01:23 main DEBUG: Crawler: web.javdb: SIMM-542: 网络错误，正在重试 (2/3): 
403 Client Error: Forbidden for url: https://www.javdb.com/search?q=SIMM-542
2021-04-27 02:01:23 web.prestige DEBUG: 无影片: SIMM-542
2021-04-27 02:01:23 main DEBUG: Crawler: web.prestige: SIMM-542: 抓取成功
2021-04-27 02:01:23 main DEBUG: Crawler: web.javdb: SIMM-542: 网络错误，正在重试 (3/3): 
403 Client Error: Forbidden for url: https://www.javdb.com/search?q=SIMM-542
2021-04-27 02:01:23 web.javbus DEBUG: 无影片: MovieInfo('SIMM-542')
2021-04-27 02:01:23 main DEBUG: Crawler: web.javbus: SIMM-542: 抓取成功
2021-04-27 02:01:24 main DEBUG: Crawler: web.jav321: SIMM-542: 抓取成功
2021-04-27 02:01:24 main DEBUG: Crawler: web.avsox: SIMM-542: 抓取成功
2021-04-27 02:01:24 web.javlib DEBUG: 'SIMM-542': 无法获取到影片结果
2021-04-27 02:01:24 main DEBUG: Crawler: web.javlib: SIMM-542: 抓取成功
2021-04-27 02:01:25 web.mgstage DEBUG: 'SIMM-542': mgstage无资源
2021-04-27 02:01:25 main DEBUG: Crawler: web.mgstage: SIMM-542: 抓取成功
2021-04-27 02:01:26 web.airav DEBUG: 'SIMM-542': airav无资源
2021-04-27 02:01:26 main DEBUG: Crawler: web.airav: SIMM-542: 抓取成功
2021-04-27 02:01:26 main DEBUG: 从'jav321'中获取了字段: cid cover duration genre genre_id plot preview_pics producer publish_date score title url
2021-04-27 02:01:26 main ERROR: 所有爬虫均未获取到字段: 'actress'，抓取失败
2021-04-27 02:01:26 main ERROR: 整理失败

最后是actress这个字段没有...直接失败

**Comment by Yuukiy** [comment]
你这其实是两个问题，前面一个已经修正了，只是还没释放: 8f4316d
后面一个主要问题不是javdb抓取不到，是mgstage的番号比较难识别，345SIMM-542识别成SIMM-542，因此抓取失败。这种番号前面还有数字的，暂时还没有好的解决办法

**Comment by chenova** [comment]
好的，谢谢回复，加油更新😀
