### ISSUE TITLE
使用微软Azure 翻译API报错

### ISSUE THREAD

**Issue by jodis** [Yuukiy/JavSP#401]
### 问题详情

求助，使用Azure 翻译API报错……

下面是翻译的配置，试过路由器挂代理，配置文件挂代理，都报这个错误。下面提供Azure 服务器上的使用截图服务应该是正常的。

```
[Translate]
\# 翻译引擎，可选: google, bing, baidu, claude(haiku), groq(llama 3.1-70b) （Google可以直接免费使用。留空表示禁用翻译功能）
\# 进阶功能的文档 https://github.com/Yuukiy/JavSP/wiki/Translation-%7C-%E7%BF%BB%E8%AF%91
engine = bing
\# 是否翻译标题
translate_title = no
\# 是否翻译剧情简介
translate_plot = yes
\# 百度翻译的APP ID和密钥
baidu_appid = 
baidu_key = 
\# 微软必应翻译（Azure 认知服务 → 翻译）的密钥
bing_key = b4ec154063f8499997503110e60091c2
\# Claude的密钥 (使用haiku模型)
claude_key = 
\# Groq的密钥 (使用llama 3.1-70b模型)
groq_key = 
```

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

```
2024-10-11 01:09:49 main:637 DEBUG: =========================JavSP v1.8=========================
2024-10-11 01:09:49 core.func:192 DEBUG: 检查版本更新时出错: SSLError(MaxRetryError("HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Yuukiy/JavSP/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))"))
2024-10-11 01:10:04 main:83 WARNING: 配置的抓取器无效: msin
2024-10-11 01:10:04 core.file:147 DEBUG: 影片数据源类型: CLUB-139: normal
2024-10-11 01:10:04 main:662 INFO: 扫描影片文件：共找到 1 部影片
2024-10-11 01:10:04 main:461 INFO: 正在整理:  [CLUB-139] .mp4
2024-10-11 01:10:04 main:112 DEBUG: web.javbus: 网络错误，正在重试 (1/3): 
SSLError(MaxRetryError("HTTPSConnectionPool(host='www.javbus.com', port=443): Max retries exceeded with url: /CLUB-139 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))"))
2024-10-11 01:10:04 main:112 DEBUG: web.jav321: 网络错误，正在重试 (1/3): 
SSLError(MaxRetryError("HTTPSConnectionPool(host='www.jav321.com', port=443): Max retries exceeded with url: /search (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))"))
2024-10-11 01:10:04 main:112 DEBUG: web.airav: 网络错误，正在重试 (1/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.airav.wiki/api/video/barcode/CLUB-139?lng=zh-TW')
2024-10-11 01:10:04 main:103 DEBUG: web.javdb: 未找到影片: 'CLUB-139'
2024-10-11 01:10:04 main:112 DEBUG: web.airav: 网络错误，正在重试 (2/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.airav.wiki/api/video/barcode/CLUB-139?lng=zh-TW')
2024-10-11 01:10:04 main:97 DEBUG: web.jav321: 抓取成功: 'CLUB-139': 'https://en.jav321.com/video/club00139'
2024-10-11 01:10:04 main:112 DEBUG: web.airav: 网络错误，正在重试 (3/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.airav.wiki/api/video/barcode/CLUB-139?lng=zh-TW')
2024-10-11 01:10:05 main:103 DEBUG: web.prestige: 未找到影片: 'CLUB-139'
2024-10-11 01:10:05 main:97 DEBUG: web.javbus: 抓取成功: 'CLUB-139': 'https://www.javbus.com/CLUB-139'
2024-10-11 01:10:05 main:103 DEBUG: web.avsox: 未找到影片: 'CLUB-139'
2024-10-11 01:10:06 main:103 DEBUG: web.mgstage: 未找到影片: 'CLUB-139'
2024-10-11 01:10:08 web.javlib:57 DEBUG: JavLib网络配置: https://www.y78k.com, proxy={}
2024-10-11 01:10:08 main:97 DEBUG: web.javlib: 抓取成功: 'CLUB-139': 'https://www.javlibrary.com/cn/?v=javliibd6y'
2024-10-11 01:10:08 main:203 DEBUG: 从'javbus'中获取了字段: actress actress_pics cover duration genre genre_id preview_pics producer publish_date publisher serial title uncensored url
2024-10-11 01:10:08 main:203 DEBUG: 从'javlib'中获取了字段: cover score
2024-10-11 01:10:08 main:203 DEBUG: 从'jav321'中获取了字段: cid cover plot preview_video
2024-10-11 01:10:08 web.translate:38 ERROR: 翻译标题时出错: bing: 401001: The request is not authorized because credentials are missing or invalid.
2024-10-11 01:10:08 main:532 DEBUG: 步骤错误
Traceback (most recent call last):
  File "JavSP.py", line 476, in RunNormalMode
  File "JavSP.py", line 452, in check_step
Exception: 步骤错误

2024-10-11 01:10:08 main:533 ERROR: 整理失败: 步骤错误
```

### 运行截图（可选）

![image](https://github.com/user-attachments/assets/f9b2fad9-c048-4f47-935e-e777e2605ef9)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by jodis** [comment]
解决了，资源组没有选择……全球……
