### ISSUE TITLE
[bug] 在整理FC2影片时出现的bug

### ISSUE THREAD

**Issue by wuabuhuan** [Yuukiy/JavSP#41]
### bug详情
在整理FC2影片时出现的问题

### 如何复现
直接选择要整理的文件夹

### 截图
<a href="https://imgtu.com/i/bmoJr6"><img src="https://s4.ax1x.com/2022/02/27/bmoJr6.png" alt="bmoJr6.png" border="0" /></a>

### 日志
2022-02-27 16:44:46 web.base DEBUG: Connectable: https://www.e59f.com HTTP 403
2022-02-27 16:44:51 main DEBUG: 由于未配置有效的fc2fan路径，已跳过该抓取器
2022-02-27 16:44:51 core.file DEBUG: 影片数据源类型: FC2-1394872: fc2
2022-02-27 16:44:51 core.file DEBUG: 影片数据源类型: FC2-2682982: fc2
2022-02-27 16:44:51 core.file DEBUG: 影片数据源类型: FC2-2683017: fc2
2022-02-27 16:44:51 main INFO: 扫描影片文件：共找到 3 部影片
2022-02-27 16:44:51 main INFO: 正在整理: FC2-PPV-1394872.mp4
2022-02-27 16:44:53 web.javdb DEBUG: 未携带有效Cookies而发生重定向，尝试更换Cookies为: ('Edge: Default', 'javdb36.com')
2022-02-27 16:44:53 web.fc2 DEBUG: 无影片: FC2-1394872
2022-02-27 16:44:53 main DEBUG: Crawler: web.fc2: FC2-1394872: 抓取成功
2022-02-27 16:44:54 web.javdb DEBUG: 未携带有效Cookies而发生重定向，尝试更换Cookies为: ('Edge: Default', 'javdb30.com')
2022-02-27 16:45:02 main ERROR: JavDB: 502 非预期状态码: https://javdb.com/v/gDmDG
2022-02-27 16:45:02 main DEBUG: JavDB: 502 非预期状态码: https://javdb.com/v/gDmDG
Traceback (most recent call last):
  File "JavSP.py", line 77, in wrapper
  File "web\javdb.py", line 109, in parse_data
  File "web\javdb.py", line 50, in get_html_wrapper
  File "web\javdb.py", line 50, in get_html_wrapper
  File "web\javdb.py", line 59, in get_html_wrapper
Exception: JavDB: 502 非预期状态码: https://javdb.com/v/gDmDG
2022-02-27 16:45:02 main ERROR: 所有爬虫均未获取到字段: 'cover'，抓取失败
2022-02-27 16:45:02 main ERROR: 整理失败: 步骤错误
2022-02-27 16:45:02 main DEBUG: 步骤错误
Traceback (most recent call last):
  File "JavSP.py", line 305, in RunNormalMode
  File "JavSP.py", line 288, in check_step
Exception: 步骤错误
2022-02-27 16:45:02 main INFO: 正在整理: hhd800.com@FC2-PPV-2682982.mp4
2022-02-27 16:45:03 main ERROR: JavDB: 502 非预期状态码: https://javdb.com/search?q=FC2-2682982
2022-02-27 16:45:03 main DEBUG: JavDB: 502 非预期状态码: https://javdb.com/search?q=FC2-2682982
Traceback (most recent call last):
  File "JavSP.py", line 77, in wrapper
  File "web\javdb.py", line 100, in parse_data
  File "web\javdb.py", line 59, in get_html_wrapper
Exception: JavDB: 502 非预期状态码: https://javdb.com/search?q=FC2-2682982
2022-02-27 16:45:04 web.fc2 DEBUG: 无影片: FC2-2682982
2022-02-27 16:45:04 main DEBUG: Crawler: web.fc2: FC2-2682982: 抓取成功
2022-02-27 16:45:04 main ERROR: 所有爬虫均未获取到字段: 'cover'，抓取失败
2022-02-27 16:45:04 main ERROR: 整理失败: 步骤错误
2022-02-27 16:45:04 main DEBUG: 步骤错误
Traceback (most recent call last):
  File "JavSP.py", line 305, in RunNormalMode
  File "JavSP.py", line 288, in check_step
Exception: 步骤错误
2022-02-27 16:45:04 main INFO: 正在整理: hhd800.com@FC2-PPV-2683017_1.mp4, hhd800.com@FC2-PPV-2683017_2.mp4
2022-02-27 16:45:06 web.fc2 DEBUG: 无影片: FC2-2683017
2022-02-27 16:45:06 main DEBUG: Crawler: web.fc2: FC2-2683017: 抓取成功
2022-02-27 16:45:13 main ERROR: JavDB: 502 非预期状态码: https://javdb.com/v/Gykn2
2022-02-27 16:45:13 main DEBUG: JavDB: 502 非预期状态码: https://javdb.com/v/Gykn2
Traceback (most recent call last):
  File "JavSP.py", line 77, in wrapper
  File "web\javdb.py", line 109, in parse_data
  File "web\javdb.py", line 59, in get_html_wrapper
Exception: JavDB: 502 非预期状态码: https://javdb.com/v/Gykn2
2022-02-27 16:45:13 main ERROR: 所有爬虫均未获取到字段: 'cover'，抓取失败
2022-02-27 16:45:13 main ERROR: 整理失败: 步骤错误
2022-02-27 16:45:13 main DEBUG: 步骤错误
Traceback (most recent call last):
  File "JavSP.py", line 305, in RunNormalMode
  File "JavSP.py", line 288, in check_step
Exception: 步骤错误

**Comment by cnqdztp** [comment]
问题同样出现
## 日志
2022-02-28 20:05:48 web.base DEBUG: Connectable: https://www.e59f.com HTTP 200
2022-02-28 20:05:51 main DEBUG: 由于未配置有效的fc2fan路径，已跳过该抓取器
2022-02-28 20:05:51 core.file DEBUG: 影片数据源类型: FC2-2298814: fc2
2022-02-28 20:05:51 core.file DEBUG: 影片数据源类型: FC2-2362891: fc2
2022-02-28 20:05:51 core.file DEBUG: 影片数据源类型: FC2-238629: fc2
2022-02-28 20:05:51 main INFO: 扫描影片文件：共找到 3 部影片
2022-02-28 20:05:51 main INFO: 正在整理: FC2-2298814.mp4
2022-02-28 20:05:51 web.base DEBUG: 无法通过CloudFlare检测: 'Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.', 尝试退回常规的requests请求
2022-02-28 20:05:52 main ERROR: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-2298814
2022-02-28 20:05:52 main DEBUG: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-2298814
Exception: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-2298814
2022-02-28 20:05:52 web.fc2 DEBUG: 无影片: FC2-2298814
2022-02-28 20:05:52 main DEBUG: Crawler: web.fc2: FC2-2298814: 抓取成功
2022-02-28 20:05:52 main ERROR: 所有爬虫均未获取到字段: 'cover'，抓取失败
2022-02-28 20:05:52 main ERROR: 整理失败: 步骤错误
2022-02-28 20:05:52 main DEBUG: 步骤错误
Exception: 步骤错误
2022-02-28 20:05:52 main INFO: 正在整理: FC2-2362891.mp4
2022-02-28 20:05:52 web.base DEBUG: 无法通过CloudFlare检测: 'Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.', 尝试退回常规的requests请求
2022-02-28 20:05:53 main ERROR: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-2362891
2022-02-28 20:05:53 main DEBUG: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-2362891
Exception: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-2362891
2022-02-28 20:05:53 web.fc2 DEBUG: 无影片: FC2-2362891
2022-02-28 20:05:53 main DEBUG: Crawler: web.fc2: FC2-2362891: 抓取成功
2022-02-28 20:05:53 main ERROR: 所有爬虫均未获取到字段: 'cover'，抓取失败
2022-02-28 20:05:53 main ERROR: 整理失败: 步骤错误
2022-02-28 20:05:53 main DEBUG: 步骤错误
Exception: 步骤错误
2022-02-28 20:05:53 main INFO: 正在整理: FC2-238629.mp4
2022-02-28 20:05:54 web.base DEBUG: 无法通过CloudFlare检测: 'Detected a Cloudflare version 2 challenge, This feature is not available in the opensource (free) version.', 尝试退回常规的requests请求
2022-02-28 20:05:54 main ERROR: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-238629
2022-02-28 20:05:54 main DEBUG: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-238629
Exception: JavDB: 503 非预期状态码: https://javdb.com/search?q=FC2-238629
2022-02-28 20:05:55 web.fc2 DEBUG: 无影片: FC2-238629
2022-02-28 20:05:55 main DEBUG: Crawler: web.fc2: FC2-238629: 抓取成功
2022-02-28 20:05:55 main ERROR: 所有爬虫均未获取到字段: 'cover'，抓取失败
2022-02-28 20:05:55 main ERROR: 整理失败: 步骤错误
2022-02-28 20:05:55 main DEBUG: 步骤错误
Exception: 步骤错误

**Comment by Yuukiy** [comment]
@wuabuhuan 从日志来看应该是触发反爬机制了，javdb的反爬机制比较严，暂时还没有办法绕开。不确定触发反爬和Cookies重试有没有关系，后面我把Cookies重试增加一点时间间隔试试。
目前临时的办法是，对于FC2类型的影片，在配置文件中配置好javdb的免代理地址以后，试着不开代理看能不能抓取到数据。

**Comment by Yuukiy** [comment]
@cnqdztp 这个情况是触发javdb的反爬机制了，而且一上来就触发，都没有提示Cookies相关的内容，不知道是不是前面还有和Cookies相关的日志。
javdb的反爬机制现在没法绕过，触发的话就会抓取失败。
目前临时的办法是，对于FC2类型的影片，在配置文件中配置好javdb的免代理地址以后，试着不开代理看能不能抓取到数据。

**Comment by wuabuhuan** [comment]
多谢，解决了！❤
