### ISSUE TITLE
一个番号多个影片的刮削问题

### ISSUE THREAD

**Issue by Arkshiaho** [Yuukiy/JavSP#411]
### 问题详情

我修改了CrawlerSelect的值

# airav avsox avwiki fanza fc2 fc2fan javbus javdb javlib javmenu jav321 mgstage prestige
[CrawlerSelect]
normal = javdb
fc2 = fc2,avsox,javdb,javmenu,fc2ppvdb
cid = fanza
getchu = dl_getchu
gyutto = gyutto

最终执行是查到了两个结果，而且我实际去javdb的网站查了确实有这两个结果

同时尝试了FAQ中在番号后加日期的方式进行刮削，结果还是一样的，使用魔法则会出现javdb禁止访问
![9566ee3eaf31a5e3f22ba7bf3f6664a7](https://github.com/user-attachments/assets/a834a034-6dd4-47df-adcd-3d005d0cd5ce)

### 运行方式

我运行的是打包后的exe程序

### 代理

否

### 日志

2024-10-21 00:58:31 core.config:431 DEBUG: 读取指定的配置文件: 'D:\tool\JavSP\manual.ini'
2024-10-21 00:58:31 main:637 DEBUG: =========================JavSP v1.8=========================
2024-10-21 00:58:34 core.file:147 DEBUG: 影片数据源类型: MIDV-018: normal
2024-10-21 00:58:34 main:662 INFO: 扫描影片文件：共找到 1 部影片
2024-10-21 00:58:34 main:395 INFO: 进入手动模式检查番号: 
2024-10-21 00:58:53 main:421 INFO: 已更正影片番号: MIDV-018-C.mp4: MIDV-018 -> MIDV-018_2021-12-21
2024-10-21 00:58:53 main:461 INFO: 正在整理: MIDV-018-C.mp4
2024-10-21 00:58:54 main:103 DEBUG: web.javdb: 未找到影片: 'MIDV-018_2021-12-21'
2024-10-21 00:58:54 main:532 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 467, in RunNormalMode
  File "JavSP.py", line 452, in check_step
Exception: 为其配置的1个抓取器均未获取到影片信息

2024-10-21 00:58:54 main:533 ERROR: 整理失败: 为其配置的1个抓取器均未获取到影片信息

2024-10-21 00:59:13 core.config:431 DEBUG: 读取指定的配置文件: 'D:\tool\JavSP\manual.ini'
2024-10-21 00:59:13 main:637 DEBUG: =========================JavSP v1.8=========================
2024-10-21 00:59:16 core.file:147 DEBUG: 影片数据源类型: MIDV-018: normal
2024-10-21 00:59:16 main:662 INFO: 扫描影片文件：共找到 1 部影片
2024-10-21 00:59:16 main:395 INFO: 进入手动模式检查番号: 
2024-10-21 00:59:22 main:421 INFO: 已更正影片番号: MIDV-018-C.mp4: MIDV-018 -> MIDV-018
2024-10-21 00:59:22 main:461 INFO: 正在整理: MIDV-018-C.mp4
2024-10-21 00:59:23 main:106 ERROR: web.javdb: 'MIDV-018': 存在2个完全匹配目标番号的搜索结果
Traceback (most recent call last):
  File "JavSP.py", line 95, in wrapper
  File "web\javdb.py", line 136, in parse_data
web.exceptions.MovieDuplicateError: web.javdb: 'MIDV-018': 存在2个完全匹配目标番号的搜索结果
2024-10-21 00:59:23 main:532 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 467, in RunNormalMode
  File "JavSP.py", line 452, in check_step
Exception: 为其配置的1个抓取器均未获取到影片信息

2024-10-21 00:59:23 main:533 ERROR: 整理失败: 为其配置的1个抓取器均未获取到影片信息

### 运行截图（可选）

![image](https://github.com/user-attachments/assets/c853a61b-f979-4328-acc7-3f4ca8508362)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by snowman** [comment]
为什么你还能使用`config.ini`配置? 最新版(v1.8) 使用的是`config.yml`, 而且为什么你还能使用`-m`选项?

番号加日期的做法只适用于 `JavBus`

**Comment by Arkshiaho** [comment]
> ~为什么你还能使用`config.ini`配置? 最新版(v1.8) 使用的是`config.yml`, 而且为什么你还能使用`-m`选项?~
> 
> ```shell
> # git的才是最新版
> $ git checkout v1.8
> $ rg add_argument
> core/config.py
> 410:    parser.add_argument('-c', '--config', help='使用指定的配置文件')
> 411:    parser.add_argument('-i', '--input', help='要扫描的文件夹')
> 412:    parser.add_argument('-o', '--output', help='保存整理结果的文件夹')
> 413:    parser.add_argument('-x', '--proxy', help='代理服务器地址')
> 414:    parser.add_argument('-m', '--manual', nargs='?', default=-1,
> 416:    parser.add_argument('-e', '--auto-exit', action='store_true', help='运行结束后自动退出')
> 417:    parser.add_argument('-s', '--shutdown', action='store_true', help='整理完成后关机')
> 418:    parser.add_argument('--data-cache-file', help='存储数据的缓存文件，临时文件，供进程间通信使用')
> 419:    parser.add_argument('--only-scan', action='store_true', help='仅识别，不刮削')
> 420:    parser.add_argument('--only-fetch', action='store_true', help='仅刮削data-cache-file缓存文件中的数据')
> ```
> 
> 番号加日期的做法只适用于 `JavBus`

那我应该怎么做才能正确刮呢，MIDV-018这个在JavBus上没有正确的内容

**Comment by snowman** [comment]
使用`git` 下载源码并修改代码逻辑, `movie.dvdid` 就是你的输入

```sh
$ git clone https://github.com/Yuukiy/JavSP
$ git checkout v1.8
$ git checkout -b my-edit
```

JavBus:
https://github.com/Yuukiy/JavSP/blob/9832462b8fc16cd1112bdf01136ad650bdf9008d/javsp/web/javbus.py#L21-L27

JavDB:
https://github.com/Yuukiy/JavSP/blob/9832462b8fc16cd1112bdf01136ad650bdf9008d/javsp/web/javdb.py#L105-L134
