### ISSUE TITLE
处理特定文件时会报错

### ISSUE THREAD

**Issue by icaca** [Yuukiy/JavSP#422]
### 问题详情

使用的docker版本

118abp00146

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

====================================
   Jav Scraper Package: 1.7.2.106
====================================

扫描影片文件...
                                   
                                       

javsp 6 <module>Error in sys.excepthook:
    writer.write_location(code.co_filename, traceback.tb_lineno, code.co_name)
  File "/app/.venv/lib/python3.12/site-packages/pretty_errors/__init__.py", line 488, in write_location
    self.output_text([
  File "/app/.venv/lib/python3.12/site-packages/pretty_errors/__init__.py", line 428, in output_text
    if count == 0 or count % line_length != 0 or self.config.full_line_newline:
                     ~~~~~~^~~~~~~~~~~~~
ZeroDivisionError: integer modulo by zero

Original exception was:
Traceback (most recent call last):
  File "/app/.venv/bin/javsp", line 6, in <module>
    sys.exit(entry())
             ^^^^^^^
  File "/app/javsp/__main__.py", line 599, in entry
    RunNormalMode(recognized + recognize_fail)
  File "/app/javsp/__main__.py", line 430, in RunNormalMode
    all_info = parallel_crawler(movie, inner_bar)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/javsp/__main__.py", line 126, in parallel_crawler
    parser = getattr(sys.modules[mod], 'parse_data')
                     ~~~~~~~~~~~^^^^^
KeyError: 'javsp.web.CrawlerID.airav'

### 运行截图（可选）

_No response_

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by icaca** [comment]
改了文件名可以了
