### ISSUE TITLE
[bug] ABW-161无法搜刮，生成不了NFO文件。但封面能下载

### ISSUE THREAD

**Issue by heptagonlin** [Yuukiy/JavSP#46]
[bug] ABW-161无法搜刮，生成不了NFO文件。但封面能下载。

2022-03-06 13:53:26 main INFO: 正在整理: ABW-161.mp4
2022-03-06 13:53:26 main DEBUG: Crawler: web.javbus: ABW-161: 抓取成功
2022-03-06 13:53:26 main DEBUG: Crawler: web.prestige: ABW-161: 抓取成功
2022-03-06 13:53:27 main DEBUG: Crawler: web.jav321: ABW-161: 抓取成功
2022-03-06 13:53:27 main DEBUG: Crawler: web.avsox: ABW-161: 抓取成功
2022-03-06 13:53:27 main DEBUG: Crawler: web.javdb: ABW-161: 抓取成功
2022-03-06 13:53:27 main DEBUG: Crawler: web.mgstage: ABW-161: 抓取成功
2022-03-06 13:53:28 main DEBUG: Crawler: web.javlib: ABW-161: 抓取成功
2022-03-06 13:53:28 main DEBUG: 从'javbus'中获取了字段: actress actress_pics cover duration genre_id preview_pics producer publish_date publisher serial title url
2022-03-06 13:53:28 main DEBUG: 从'javdb'中获取了字段: magnet preview_video score
2022-03-06 13:53:28 main DEBUG: 从'javlib'中获取了字段: director
2022-03-06 13:53:28 main DEBUG: 从'jav321'中获取了字段: cid
2022-03-06 13:53:28 main DEBUG: 从'mgstage'中获取了字段: plot
2022-03-06 13:53:28 main DEBUG: 从'prestige'中获取了字段: big_cover
2022-03-06 13:53:28 core.datatype INFO: 重命名文件: 'ABW-161.mp4' -> '...\ABW-161.mp4'
2022-03-06 13:53:29 main DEBUG: 图片不完整，尝试重新下载: 'https://www.javsee.us/pics/cover/8kb4_b.jpg'
2022-03-06 13:53:31 main DEBUG: 图片不完整，尝试重新下载: 'https://www.javsee.us/pics/cover/8kb4_b.jpg'
2022-03-06 13:53:32 main DEBUG: 图片不完整，尝试重新下载: 'https://www.javsee.us/pics/cover/8kb4_b.jpg'
2022-03-06 13:53:32 main ERROR: 下载封面图片失败: 'https://www.javsee.us/pics/cover/8kb4_b.jpg'
2022-03-06 13:53:32 main ERROR: 整理失败: 步骤错误
2022-03-06 13:53:32 main DEBUG: 步骤错误
Traceback (most recent call last):
  File "JavSP.py", line 321, in RunNormalMode
  File "JavSP.py", line 288, in check_step
Exception: 步骤错误

**Comment by Yuukiy** [comment]
已添加处理机制，可到 https://github.com/Yuukiy/JavSP/actions/workflows/pyinstaller.yml 下载临时版
