### ISSUE TITLE
抓取的文件名有非法字符“\n”，导致刮削失败。希望增加去除非法字符的代码。

### ISSUE THREAD

**Issue by hai9740** [Yuukiy/JavSP#467]
### 问题详情

取消百度翻译后成功。
![image](https://github.com/user-attachments/assets/579eaa60-2527-4bf8-b205-89831216e21d)

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

2024-12-12 17:36:28 main:637 DEBUG: =========================JavSP v1.8=========================
2024-12-12 17:36:29 core.file:147 DEBUG: 影片数据源类型: heydouga-4030-2072: normal
2024-12-12 17:36:29 main:662 INFO: 扫描影片文件：共找到 1 部影片
2024-12-12 17:36:29 main:461 INFO: 正在整理: heydouga-4030-2072.wmv
2024-12-12 17:36:29 main:109 ERROR: prestige不允许从当前IP所在地区访问，请尝试更换为日本地区代理
2024-12-12 17:36:29 main:103 DEBUG: web.jav321: 未找到影片: 'heydouga-4030-2072'
2024-12-12 17:36:29 main:109 ERROR: mgstage不允许从当前IP所在地区访问，请尝试更换为日本地区代理
2024-12-12 17:36:29 main:112 DEBUG: web.airav: 网络错误，正在重试 (1/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.airav.wiki/api/video/barcode/heydouga-4030-2072?lng=zh-TW')
2024-12-12 17:36:30 main:103 DEBUG: web.avsox: 未找到影片: 'heydouga-4030-2072'
2024-12-12 17:36:30 main:112 DEBUG: web.airav: 网络错误，正在重试 (2/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.airav.wiki/api/video/barcode/heydouga-4030-2072?lng=zh-TW')
2024-12-12 17:36:30 main:97 DEBUG: web.javdb: 抓取成功: 'heydouga-4030-2072': 'https://javdb.com/v/M7mDk'
2024-12-12 17:36:31 main:103 DEBUG: web.javbus: 未找到影片: 'heydouga-4030-2072'
2024-12-12 17:36:31 main:112 DEBUG: web.airav: 网络错误，正在重试 (3/3): 
HTTPError('403 Client Error: Forbidden for url: https://www.airav.wiki/api/video/barcode/heydouga-4030-2072?lng=zh-TW')
2024-12-12 17:36:31 web.javlib:46 WARNING: 无法绕开JavLib的反爬机制
2024-12-12 17:36:31 web.javlib:57 DEBUG: JavLib网络配置: https://www.javlibrary.com, proxy={}
2024-12-12 17:36:36 web.base:60 DEBUG: 无法通过CloudFlare检测: 'HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=heydouga-4030-2072 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))', 尝试退回常规的requests请求
2024-12-12 17:36:41 main:112 DEBUG: web.javlib: 网络错误，正在重试 (1/3): 
ProxyError(MaxRetryError("HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=heydouga-4030-2072 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))"))
2024-12-12 17:36:46 web.base:60 DEBUG: 无法通过CloudFlare检测: 'HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=heydouga-4030-2072 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))', 尝试退回常规的requests请求
2024-12-12 17:36:51 main:112 DEBUG: web.javlib: 网络错误，正在重试 (2/3): 
ProxyError(MaxRetryError("HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=heydouga-4030-2072 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))"))
2024-12-12 17:36:56 web.base:60 DEBUG: 无法通过CloudFlare检测: 'HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=heydouga-4030-2072 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))', 尝试退回常规的requests请求
2024-12-12 17:37:01 main:203 DEBUG: 从'javdb'中获取了字段: actress cover duration genre_id magnet producer publish_date score serial title uncensored url
2024-12-12 17:37:01 main:112 DEBUG: web.javlib: 网络错误，正在重试 (3/3): 
ProxyError(MaxRetryError("HTTPSConnectionPool(host='www.javlibrary.com', port=443): Max retries exceeded with url: /cn/vl_searchbyid.php?keyword=heydouga-4030-2072 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))"))
2024-12-12 17:37:01 core.file:213 DEBUG: 目标路径是远程文件系统
2024-12-12 17:37:01 main:333 INFO: 自动截短原始标题为:
みづなれい - 同時挿入の二穴姦 コスプレ中出し
2024-12-12 17:37:01 main:532 DEBUG: [WinError 123] 文件名、目录名或卷标语法不正确。: '#整理完成\\みづなれい\\[heydouga-4030-2072] 推荐\n同时插入的二穴奸角色扮演中出'
Traceback (most recent call last):
  File "JavSP.py", line 481, in RunNormalMode
  File "os.py", line 223, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: '#整理完成\\みづなれい\\[heydouga-4030-2072] 推荐\n同时插入的二穴奸角色扮演中出'
Arguments: 
  '文件名、目录名或卷标语法不正确。'
2024-12-12 17:37:01 main:533 ERROR: 整理失败: [WinError 123] 文件名、目录名或卷标语法不正确。: '#整理完成\\みづなれい\\[heydouga-4030-2072] 推荐\n同时插入的二穴奸角色扮演中出'

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by glyh** [comment]
不太理解，这个番号完整的形式是啥样的？

`Heydouga 4030-PPV2072` ？

**Comment by glyh** [comment]
好像windows下不支持文件名加换行，我的linux下没有这样的问题。

Nevertheless 我待会加一个commit过滤下文件名好了

**Comment by glyh** [comment]
已fix，麻烦测试下master。

我的电脑是linux所以没法测试
