### ISSUE TITLE
能否解决无法绕过javlib网站的反爬机制

### ISSUE THREAD

**Issue by Lkskywalker** [Yuukiy/JavSP#488]
### 问题详情

无法绕过javlib网站的反爬机制，只有这个站的影片最全，但是无法绕开，导致无法爬取

### 运行方式

我运行的是打包后的exe程序

### 代理

是

### 日志

2024-12-25 00:40:18 main:461 INFO: 正在整理: savr-517-cd1.mp4, savr-517-cd2.mp4
2024-12-25 00:40:18 main:112 DEBUG: web.javlib: 网络错误，正在重试 (1/3): 
HTTPError('429 Client Error: Too Many Requests for url: https://www.javlibrary.com/cn/vl_searchbyid.php?keyword=savr-517')
2024-12-25 00:40:18 main:112 DEBUG: web.javlib: 网络错误，正在重试 (2/3): 
HTTPError('429 Client Error: Too Many Requests for url: https://www.javlibrary.com/cn/vl_searchbyid.php?keyword=savr-517')
2024-12-25 00:40:18 main:112 DEBUG: web.javlib: 网络错误，正在重试 (3/3): 
HTTPError('429 Client Error: Too Many Requests for url: https://www.javlibrary.com/cn/vl_searchbyid.php?keyword=savr-517')
2024-12-25 00:40:18 main:532 DEBUG: 为其配置的1个抓取器均未获取到影片信息
Traceback (most recent call last):
  File "JavSP.py", line 467, in RunNormalMode
  File "JavSP.py", line 452, in check_step
Exception: 为其配置的1个抓取器均未获取到影片信息

2024-12-25 00:40:18 main:533 ERROR: 整理失败: 为其配置的1个抓取器均未获取到影片信息

### 运行截图（可选）

![image](https://github.com/user-attachments/assets/45b09558-e71e-40fe-9a2d-8297e9299345)

### 提交须知

- [X] 我确认使用的是最新版本并且阅读过Wiki帮助文档
- [X] 我确认已经搜索过Issue区，没有与我遇到的情况相同的Issue。

**Comment by lxnan888** [comment]
你的配置文件是ini格式还是yml格式

**Comment by Lkskywalker** [comment]
> 你的配置文件是ini格式还是yml格式
ini格式，下载的是打包好的exe，ini是第一次运行后自动生成的

**Comment by 3213778453** [comment]
有Cloudflare的是不是最难的？
