### ISSUE TITLE
[bug] 刮削的时候还是有不稳定的情况出现。

### ISSUE THREAD

**Issue by heptagonlin** [Yuukiy/JavSP#50]
2022-03-08 20:07:29 main INFO: 正在整理: 259LUXU-1184.mp4
2022-03-08 20:07:29 web.javlib DEBUG: 'LUXU-1184': 无法获取到影片结果
2022-03-08 20:07:29 main DEBUG: Crawler: web.javlib: LUXU-1184: 抓取成功
2022-03-08 20:07:29 main DEBUG: Crawler: web.mgstage: LUXU-1184: 网络错误，正在重试 (1/3): 
SSLError(MaxRetryError("HTTPSConnectionPool(host='www.mgstage.com', port=443): Max retries exceeded with url: /product/product_detail/LUXU-1184/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))"))
2022-03-08 20:07:29 web.prestige DEBUG: Prestige无影片: MovieInfo('LUXU-1184')
2022-03-08 20:07:29 main DEBUG: Crawler: web.prestige: LUXU-1184: 抓取成功
2022-03-08 20:07:30 main DEBUG: Crawler: web.jav321: LUXU-1184: 抓取成功
2022-03-08 20:07:30 main DEBUG: Crawler: web.avsox: LUXU-1184: 抓取成功
2022-03-08 20:07:30 main DEBUG: Crawler: web.javdb: LUXU-1184: 抓取成功
2022-03-08 20:07:30 web.javbus DEBUG: JavBus无影片: MovieInfo('LUXU-1184')
2022-03-08 20:07:30 main DEBUG: Crawler: web.javbus: LUXU-1184: 抓取成功
2022-03-08 20:07:31 web.mgstage DEBUG: 'LUXU-1184': mgstage无资源
2022-03-08 20:07:31 main DEBUG: Crawler: web.mgstage: LUXU-1184: 抓取成功
2022-03-08 20:07:31 main DEBUG: 从'javdb'中获取了字段: actress cover duration genre_id magnet preview_pics preview_video producer publish_date score title url
2022-03-08 20:07:31 main DEBUG: 从'jav321'中获取了字段: cid
2022-03-08 20:07:31 core.datatype INFO: 重命名文件: '259LUXU 1100-1199\259LUXU-1184 【有码】 【1080P】\259LUXU-1184.mp4' -> '...\LUXU-1184.mp4'
2022-03-08 20:07:31 main ERROR: 整理失败: HTTPSConnectionPool(host='jdbimgs.com', port=443): Max retries exceeded with url: /covers/v8/V8JnD.jpg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
2022-03-08 20:07:31 main DEBUG: HTTPSConnectionPool(host='jdbimgs.com', port=443): Max retries exceeded with url: /covers/v8/V8JnD.jpg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jdbimgs.com', port=443): Max retries exceeded with url: /covers/v8/V8JnD.jpg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JavSP.py", line 320, in RunNormalMode
  File "JavSP.py", line 368, in download_cover
  File "web\base.py", line 207, in download
  File "web\base.py", line 181, in urlretrieve
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='jdbimgs.com', port=443): Max retries exceeded with url: /covers/v8/V8JnD.jpg (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

**Comment by heptagonlin** [comment]
我用其他刮削软件就能成功刮削
